ALTER TABLE cw20token_info ADD COLUMN IF NOT EXISTS type    TEXT NULL;
ALTER TABLE cw20token_info ADD COLUMN IF NOT EXISTS creator TEXT NOT NULL;

ALTER TABLE cw20token_balance 
ALTER COLUMN balance TYPE TEXT;