version: '3.6'
services:
  bdjuno:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${HASURA_ACTIONS_PORT}:3286"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: ${LOGGING_DRIVER}
  hasura:
    image: hasura/graphql-engine:v2.3.1
    ports:
      - "${HASURA_PORT}:8080"
    logging:
      driver: ${LOGGING_DRIVER}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE}
      HASURA_GRAPHQL_DEV_MODE: ${HASURA_GRAPHQL_DEV_MODE}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: ${HASURA_GRAPHQL_ENABLED_LOG_TYPES}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}
      ACTION_BASE_URL: ${ACTION_BASE_URL}

