version: '3.6'
services:
  bdjuno:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # volumes:
    #   - /usr/local/bdjuno/.bdjuno/:/usr/local/bdjuno/.bdjuno/
