version: '3.6'
services:
  bdjuno:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${HASURA_ACTIONS_PORT}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: ${LOGGING_DRIVER}
    depends_on:
      - cloudsql-proxy
  hasura:
    image: hasura/graphql-engine:v2.3.1
    ports:
      - "${HASURA_PORT}:8080"
    logging:
      driver: ${LOGGING_DRIVER}
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE}
      HASURA_GRAPHQL_DEV_MODE: ${HASURA_GRAPHQL_DEV_MODE}
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: ${HASURA_GRAPHQL_ENABLED_LOG_TYPES}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: ${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}
    depends_on:
      - cloudsql-proxy
      - hasura-actions
  cloudsql-proxy:
    container_name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: /cloud_sql_proxy --dir=/cloudsql -instances=${GCLOUD_INSTANCE_CONNECTION_NAME}=tcp:0.0.0.0:5432
    ports:
      - 5432:5432
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${GCLOUD_INSTANCE_CONNECTION_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
