chain:
    bech32_prefix: cudos
    modules: 
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - slashing 
        - staking
        - pricefeed
        - distribution
        - cosmwasm
        - gravity
        - cudomint
        - nft
        - marketplace
        - actions
        - feegrant
        - group
node:
    type: remote
    config:
        rpc:
            client_name: cudos-network
            address: http://34.121.218.76:26657
            max_connections: 20
        grpc:
            address: http://34.121.218.76:9090
            insecure: true
parsing:
    workers: 2
    last_upgrade_height: 0
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: false # when fast sync is set to true, ignores all previous block
    genesis_file_path: /usr/local/bdjuno/bdjuno/genesis.json
database:
    url: postgres://%POSTGRES_USER%:%POSTGRES_PASSWORD%@host:5432/database-name?sslmode=disable&search_path=public
    max_open_connections: 10
    max_idle_connections: 10
    partition_size: 100000
    partition_batch: 1000
logging:
    level: debug
    format: text
telemetry:
    port: 5000
pricefeed:
    tokens:
        - name: Cudos
          units:
            - denom: cudos
              exponent: 0
              price_id: cudos
distribution:
    rewards_frequency: 1000
workers:
    - name: fix_blocks_worker
      interval: 60m
    - name: blocks_monitoring_worker
      interval: 30s
cudomint:
    stats_service_url: http://127.0.0.1:3000
crypto-compare:
    crypto_compare_prod_api_key: %CRYPTO_COMPARE_PROD_API_KEY%
    crypto_compare_free_api_key: %CRYPTO_COMPARE_FREE_API_KEY%
actions:
    port: 3286
