version: '3.6'
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "6666:5432"
    environment:
      POSTGRES_DB: bdjuno_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres