version: '3.6'
services:
  postgres:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "6666:5432"
    environment:
      POSTGRES_DB: bdjuno_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
  tests:
    build:
      context: ../
      dockerfile: ./integration_tests/Dockerfile
    depends_on:
      - postgres
