# example config for bdJuno - place it in your home folder (by default ~/.bdjuno)
chain:
    bech32_prefix: cudos
    modules: 
        - modules
        - messages
        - auth
        - bank
        - consensus
        - gov
        - slashing 
        - staking
        - history
        - pricefeed
        - cosmwasm
        - gravity
        - cudomint
        - nft
        - group
        - marketplace
        - cw20token
node:
    type: remote
    config:
        rpc:
            client_name: cudos-network
            address: http://localhost:26657
            max_connections: 20
        grpc:
            address: http://localhost:9090
            insecure: true
parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    fast_sync: false # when fast sync is set to true, ignores all previous block
    genesis_file_path: samplePath
database:
    name: LocalBigDipperTest
    host: localhost
    port: 5432
    user: postgres
    password: samplePassword
    schema: public
    max_open_connections: 10
    max_idle_connections: 10
logging:
    level: debug
    format: text
telemetry:
    port: 5000
workers:
    - name: fix_blocks_worker
      interval: 60m
    - name: migrate_nfts_worker
      interval: 1m
    - name: blocks_monitoring_worker
      interval: 30s
cudomint:
    stats_service_url: http://127.0.0.1:3000