name: Deploy BDJuno on public testnet

#on:
#  push:
#    branches:
#      - main

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: cudos-public-testnet-explorer-02
    steps:
      - name: Apply Hasura metadata
        run: |
          cd hasura
          curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
          echo "script finished"
          pwd
          cat << EOF > diag.file
          hasura metadata apply --endpoint ${{ secrets.HASURA_GRAPHQL_ENDPOINT_URL }} --admin-secret ${{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}
          EOF
          chmod +x diag.file
          ./diag.file
