name: Deploy BDJuno on public testnet

#on:
#  push:
#    branches:
#      - main

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: cudos-public-testnet-explorer-02
    steps:
      - name: Apply Hasura metadata
        run: |
          cd hasura
          pwd
          ./diag.file
